/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SuppliersIndexImport } from './routes/suppliers/index'
import { Route as ProductListIndexImport } from './routes/product-list/index'
import { Route as ProductDetailIndexImport } from './routes/product-detail/index'
import { Route as CategoriesIndexImport } from './routes/categories/index'
import { Route as CategoryCategoryIdImport } from './routes/category/$categoryId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SuppliersIndexRoute = SuppliersIndexImport.update({
  path: '/suppliers/',
  getParentRoute: () => rootRoute,
} as any)

const ProductListIndexRoute = ProductListIndexImport.update({
  path: '/product-list/',
  getParentRoute: () => rootRoute,
} as any)

const ProductDetailIndexRoute = ProductDetailIndexImport.update({
  path: '/product-detail/',
  getParentRoute: () => rootRoute,
} as any)

const CategoriesIndexRoute = CategoriesIndexImport.update({
  path: '/categories/',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryIdRoute = CategoryCategoryIdImport.update({
  path: '/category/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/product-detail/': {
      id: '/product-detail/'
      path: '/product-detail'
      fullPath: '/product-detail'
      preLoaderRoute: typeof ProductDetailIndexImport
      parentRoute: typeof rootRoute
    }
    '/product-list/': {
      id: '/product-list/'
      path: '/product-list'
      fullPath: '/product-list'
      preLoaderRoute: typeof ProductListIndexImport
      parentRoute: typeof rootRoute
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/product-detail': typeof ProductDetailIndexRoute
  '/product-list': typeof ProductListIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/product-detail': typeof ProductDetailIndexRoute
  '/product-list': typeof ProductListIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/product-detail/': typeof ProductDetailIndexRoute
  '/product-list/': typeof ProductListIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category/$categoryId'
    | '/categories'
    | '/product-detail'
    | '/product-list'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category/$categoryId'
    | '/categories'
    | '/product-detail'
    | '/product-list'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/category/$categoryId'
    | '/categories/'
    | '/product-detail/'
    | '/product-list/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProductDetailIndexRoute: typeof ProductDetailIndexRoute
  ProductListIndexRoute: typeof ProductListIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProductDetailIndexRoute: ProductDetailIndexRoute,
  ProductListIndexRoute: ProductListIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/category/$categoryId",
        "/categories/",
        "/product-detail/",
        "/product-list/",
        "/suppliers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/category/$categoryId": {
      "filePath": "category/$categoryId.tsx"
    },
    "/categories/": {
      "filePath": "categories/index.tsx"
    },
    "/product-detail/": {
      "filePath": "product-detail/index.tsx"
    },
    "/product-list/": {
      "filePath": "product-list/index.tsx"
    },
    "/suppliers/": {
      "filePath": "suppliers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
